name: Nightly data refresh

on:
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC nightly
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn streamlit pulp pytest openpyxl xlrd

      - name: Run data validation tests
        run: pytest

      - name: Refresh KPI exports
        run: python -m analytics.kpi

      - name: Upload KPI outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kpi-refresh
          path: |
            outputs/kpi_summary.csv
            outputs/kpi_overview.json
          if-no-files-found: warn
